export enum SlugedNamePermission {
  CREATE_USER = 'create-user',
  READ_USER = 'read-user',
  UPDATE_USER = 'update-user',
  DELETE_USER = 'delete-user',
  INACTIVATE_USER = 'inactivate-user',
  ACTIVATE_USER = 'activate-user',
  FIND_BY_EMAIL_USER = 'find-by-email-user',
  ASSIGN_ROLES_TO_USER = 'assign-roles-to-user',
  ASSIGN_PERMISSIONS_TO_USER = 'assign-permissions-to-user',
  FIND_ALL_PERMISSIONS_OF_USER = 'find-all-permissions-of-user',
  GET_ME_DATA = 'get-me-data',
  CREATE_ROLE = 'create-role',
  READ_ROLE = 'read-role',
  UPDATE_ROLE = 'update-role',
  DELETE_ROLE = 'delete-role',
  ASSIGN_PERMISSIONS_TO_ROLE = 'assign-permissions-to-role',
  READ_PERMISSIONS = 'read-permissions',
  DELETE_PERMISSION = 'delete-permission',
}
