version: '3.8'

services:
  nest-api-dev:
    container_name: ${DOCKER_CONTAINER_NAME}
    image: ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG:-latest}
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    command: yarn run start:dev
    ports:
      - 3000:3000
    restart: unless-stopped
