version: '3.8'

services:
  nest-api-template:
    container_name: nest-api-template
    image: ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}
    env_file:
      - .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${PORT}:${PORT}
    restart: always

networks:
  default:
    name: servidor-pruebas
    external: true
