INSERT INTO permissions(`id`, `name`, `sluged_name`, `group`) VALUES
(1, 'Create user', 'create-user', 'Users'),
(2, 'Read users', 'read-users', 'Users'),
(3, 'Read user', 'read-user', 'Users'),
(4, 'Update user', 'update-user', 'Users'),
(5, 'Delete user', 'delete-user', 'Users'),
(6, 'Inactive user', 'inactive-user', 'Users'),
(7, 'Activate user', 'activate-user', 'Users'),
(8, 'Find by email user', 'find-by-email-user', 'Users'),
(9, 'Assign roles to user', 'assign-roles-to-user', 'Users'),
(10, 'Assign permissions to user', 'assign-permissions-to-user', 'Users'),
(11, 'Find all permissions of user', 'find-all-permissions-of-user', 'Users'),
(12, 'Get data about me', 'get-data-about-me', 'Auth'),
(13, 'Create role', 'create-role', 'Roles'),
(14, 'Read roles', 'read-roles', 'Roles'),
(15, 'Read role', 'read-role', 'Roles'),
(16, 'Update role', 'update-role', 'Roles'),
(17, 'Delete role', 'delete-role', 'Roles'),
(18, 'Assign permissions to role', 'assign-permissions-to-role', 'Roles'),
(19, 'Read permissions', 'read-permissions', 'Permissions'),
(20, 'Read permission', 'read-permission', 'Permissions'),
(21, 'Delete permission', 'delete-permission', 'Permissions');

INSERT INTO user_permission (`permission_id`, `user_id`) VALUES 
(1, 1),
(2, 1),
(3, 1),
(4, 1),
(5, 1),
(6, 1),
(7, 1),
(8, 1),
(9, 1),
(10, 1),
(11, 1),
(12, 1),
(13, 1),
(14, 1),
(15, 1),
(16, 1),
(17, 1),
(18, 1),
(19, 1),
(20, 1),
(21, 1);